<a href="https://colab.research.google.com/github/AgaWoj/data_science/blob/main/NumPyIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.__version__

'1.23.5'

## https://github.com/krakowiakpawel9/data-science-bootcamp/blob/master/01_wprowadzenie/01_numpy_intro.ipynb

In [3]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 

In [4]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [5]:
# Tablica jednowymiarowa

x = np.array([1,3])
x

array([1, 3])

In [6]:
type(x)

numpy.ndarray

In [7]:
# wymiar tablicy

x.ndim

1

In [8]:
# kształt
# tupla, 2 elementy

x.shape

(2,)

In [9]:
# rozmiar

x.size

2

In [10]:
# typ danych

x.dtype

dtype('int64')

In [11]:
x = np.array([1.3, 2.3, 1.4])
x

array([1.3, 2.3, 1.4])

In [12]:
x.dtype

dtype('float64')

## Tablice dwuwymiarowe - 2D ARRAY

In [13]:
# lista w liście [[]]

x = np.array([[1,2], [-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [14]:
x.dtype

dtype('int64')

In [15]:
x.size

4

In [16]:
x.shape

(2, 2)

In [17]:
x.ndim

2

In [18]:
x = np.array([[1,2,4], [4,2,1]])
x

array([[1, 2, 4],
       [4, 2, 1]])

In [19]:
# tablica 2 na 3, 2 wiersze i trzy kolumny
x.shape

(2, 3)

## 3D Array - tablica trójwymiarowa

In [20]:
x = np.array(
    [[[4,3,1],
      [3,2,1]],

     [[4,1,3],
      [4,2,1]],

     [[3,2,1],
      [4,3,2]]]
)
x

array([[[4, 3, 1],
        [3, 2, 1]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [21]:
x.ndim

3

In [22]:
# trzy tablice, dwa wiersze, trzy kolumny

x.shape

(3, 2, 3)

## Typy danych

In [23]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [24]:
a = np.array([1.2,3.4,5])
a.dtype

dtype('float64')

In [25]:
# można ustawić parametr dtype
a = np.array([1,4,6], dtype='float')
a.dtype

dtype('float64')

In [26]:
# konwertowanie na liczby złożone
a = np.array([1,2,3], dtype='complex')
a.dtype

dtype('complex128')

In [27]:
a

array([1.+0.j, 2.+0.j, 3.+0.j])

In [28]:
# float na int - trzeba uważać, bo przestawi na int
a = np.array([1.2,3.4,5.6], dtype='int')
a.dtype

dtype('int64')

In [29]:
a

array([1, 3, 5])

In [30]:
a = np.array([True, False])
a.dtype

dtype('bool')

In [31]:
# int8 - ośmiobitowa liczba całkowita
a = np.array([24,120,240], dtype=np.int8)
a.dtype

dtype('int8')

In [32]:
a = np.array([24,120,240], dtype=np.uint8)
a.dtype

dtype('uint8')