<a href="https://colab.research.google.com/github/AgaWoj/data_science/blob/main/NumPyIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.__version__

'1.23.5'

## https://github.com/krakowiakpawel9/data-science-bootcamp/blob/master/01_wprowadzenie/01_numpy_intro.ipynb

In [3]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 

In [4]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [5]:
# Tablica jednowymiarowa

x = np.array([1,3])
x

array([1, 3])

In [6]:
type(x)

numpy.ndarray

In [7]:
# wymiar tablicy

x.ndim

1

In [8]:
# kształt
# tupla, 2 elementy

x.shape

(2,)

In [9]:
# rozmiar

x.size

2

In [10]:
# typ danych

x.dtype

dtype('int64')

In [11]:
x = np.array([1.3, 2.3, 1.4])
x

array([1.3, 2.3, 1.4])

In [12]:
x.dtype

dtype('float64')

## Tablice dwuwymiarowe - 2D ARRAY

In [13]:
# lista w liście [[]]

x = np.array([[1,2], [-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [14]:
x.dtype

dtype('int64')

In [15]:
x.size

4

In [16]:
x.shape

(2, 2)

In [17]:
x.ndim

2

In [18]:
x = np.array([[1,2,4], [4,2,1]])
x

array([[1, 2, 4],
       [4, 2, 1]])

In [19]:
# tablica 2 na 3, 2 wiersze i trzy kolumny
x.shape

(2, 3)

## 3D Array - tablica trójwymiarowa

In [20]:
x = np.array(
    [[[4,3,1],
      [3,2,1]],

     [[4,1,3],
      [4,2,1]],

     [[3,2,1],
      [4,3,2]]]
)
x

array([[[4, 3, 1],
        [3, 2, 1]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [21]:
x.ndim

3

In [22]:
# trzy tablice, dwa wiersze, trzy kolumny

x.shape

(3, 2, 3)

## Typy danych

In [23]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [24]:
a = np.array([1.2,3.4,5])
a.dtype

dtype('float64')

In [25]:
# można ustawić parametr dtype
a = np.array([1,4,6], dtype='float')
a.dtype

dtype('float64')

In [26]:
# konwertowanie na liczby złożone
a = np.array([1,2,3], dtype='complex')
a.dtype

dtype('complex128')

In [27]:
a

array([1.+0.j, 2.+0.j, 3.+0.j])

In [28]:
# float na int - trzeba uważać, bo przestawi na int
a = np.array([1.2,3.4,5.6], dtype='int')
a.dtype

dtype('int64')

In [29]:
a

array([1, 3, 5])

In [30]:
a = np.array([True, False])
a.dtype

dtype('bool')

In [31]:
# int8 - ośmiobitowa liczba całkowita
a = np.array([24,120,240], dtype=np.int8)
a.dtype

dtype('int8')

In [32]:
a = np.array([24,120,240], dtype=np.uint8)
a.dtype

dtype('uint8')

## Tworzenie tablic

In [34]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [36]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [37]:
np.ones(shape=(4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [39]:
# metoda full może ustawić konkretne wartości

np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [40]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [43]:
np.arange(start=5, stop=10, step=0.5)

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [47]:
np.arange(start=100, stop=10, step= -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [49]:
np.arange(start = 0, stop = 1, step = 0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [53]:
# num - mówi ile elementów równo rozłozonych chcemy wygenerować z podanego zakresu

np.linspace(start=0, stop=1, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## Zmiana kształtu danych

In [54]:
# reshape

a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [56]:
# ustawiamy na co chcemy zmienić, 15 dzieli się na 3 po 5

a.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [57]:
# - 1 => powoduje, że python sam wybierze ile kolum w posiadanych liczb powstanie, my tylko podajemy liczbę wierszy

a.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [58]:
# można też podać na odwrót czyli liczbę kolum a liczba wierszy zostanie automatycznie dobrana

a.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Podstawowe operacje na tablicach

In [59]:
a = np.array([1,2,3,4])
b = np.array([3,-1,3,2])


In [60]:
a

array([1, 2, 3, 4])

In [61]:
b

array([ 3, -1,  3,  2])

In [62]:
a + b

array([4, 1, 6, 6])

In [63]:
a-b

array([-2,  3,  0,  2])

In [64]:
a*b

array([ 3, -2,  9,  8])

In [65]:
a/b

array([ 0.33333333, -2.        ,  1.        ,  2.        ])

In [66]:
a + 3

array([4, 5, 6, 7])

In [67]:
2 * a

array([2, 4, 6, 8])

In [68]:
a + 3 * b

array([10, -1, 12, 10])

In [70]:
np.add(a,b)

array([4, 1, 6, 6])

In [71]:
np.subtract(a,b)

array([-2,  3,  0,  2])

In [72]:
np.multiply(a,b)

array([ 3, -2,  9,  8])

In [73]:
np.divide(a,b)

array([ 0.33333333, -2.        ,  1.        ,  2.        ])

## Mnożenie macierzowe

In [74]:
x = np.array([[1,3], [-2,0]])
y = np.array([[6,0], [-1,2]])

In [79]:
print(x, '\n'), print(y)
#'\n' - linia przerwy

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


(None, None)

In [85]:
x * y

array([[6, 0],
       [2, 0]])

In [81]:
# metoda np.dot() - to mnożenie macierzy

# 1 * 6 + 3 * -1 = 3 - pierwszy wiersz pierwsza kolumna, ________.  1 * 0 + 3 * 2 = 6 - pierwszy wiersz druga kolumna
# -2 * 6 + 0 * -1 = -12 - drugi wiersz pierwsza kolumna     _________     # 1 * 0 + 3 * 0 = 0 - prawy dolny róg - drugi wiersz druga kolumna

#

np.dot(x,y)

# to nam zwraca mnożenie macierzowe, wiersz x kolumna i wiersz x kolumna

array([[  3,   6],
       [-12,   0]])

In [86]:
x.dot(y)

array([[  3,   6],
       [-12,   0]])

In [87]:
y.dot(x)

array([[ 6, 18],
       [-5, -3]])

In [ ]:
# liczba kolumn w pierwszej macierzy musi zgadzać się z liczbą wierszy w drugiej macierzy

# [m x n] [n x p]

# w rezultacie dostanę [m x p] - narożne
# monożenie macierzy nie jest przemienne