<a href="https://colab.research.google.com/github/AgaWoj/data_science/blob/main/NumPyIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [85]:
import numpy as np

In [2]:
np.__version__

'1.23.5'

## https://github.com/krakowiakpawel9/data-science-bootcamp/blob/master/01_wprowadzenie/01_numpy_intro.ipynb

In [3]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 

In [4]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [5]:
# Tablica jednowymiarowa

x = np.array([1,3])
x

array([1, 3])

In [6]:
type(x)

numpy.ndarray

In [7]:
# wymiar tablicy

x.ndim

1

In [8]:
# kształt
# tupla, 2 elementy

x.shape

(2,)

In [9]:
# rozmiar

x.size

2

In [10]:
# typ danych

x.dtype

dtype('int64')

In [11]:
x = np.array([1.3, 2.3, 1.4])
x

array([1.3, 2.3, 1.4])

In [12]:
x.dtype

dtype('float64')

## Tablice dwuwymiarowe - 2D ARRAY

In [13]:
# lista w liście [[]]

x = np.array([[1,2], [-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [14]:
x.dtype

dtype('int64')

In [15]:
x.size

4

In [16]:
x.shape

(2, 2)

In [17]:
x.ndim

2

In [18]:
x = np.array([[1,2,4], [4,2,1]])
x

array([[1, 2, 4],
       [4, 2, 1]])

In [19]:
# tablica 2 na 3, 2 wiersze i trzy kolumny
x.shape

(2, 3)

## 3D Array - tablica trójwymiarowa

In [20]:
x = np.array(
    [[[4,3,1],
      [3,2,1]],

     [[4,1,3],
      [4,2,1]],

     [[3,2,1],
      [4,3,2]]]
)
x

array([[[4, 3, 1],
        [3, 2, 1]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [21]:
x.ndim

3

In [22]:
# trzy tablice, dwa wiersze, trzy kolumny

x.shape

(3, 2, 3)

## Typy danych

In [23]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [24]:
a = np.array([1.2,3.4,5])
a.dtype

dtype('float64')

In [25]:
# można ustawić parametr dtype
a = np.array([1,4,6], dtype='float')
a.dtype

dtype('float64')

In [26]:
# konwertowanie na liczby złożone
a = np.array([1,2,3], dtype='complex')
a.dtype

dtype('complex128')

In [27]:
a

array([1.+0.j, 2.+0.j, 3.+0.j])

In [28]:
# float na int - trzeba uważać, bo przestawi na int
a = np.array([1.2,3.4,5.6], dtype='int')
a.dtype

dtype('int64')

In [29]:
a

array([1, 3, 5])

In [30]:
a = np.array([True, False])
a.dtype

dtype('bool')

In [31]:
# int8 - ośmiobitowa liczba całkowita
a = np.array([24,120,240], dtype=np.int8)
a.dtype

dtype('int8')

In [32]:
a = np.array([24,120,240], dtype=np.uint8)
a.dtype

dtype('uint8')

## Tworzenie tablic

In [33]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [35]:
np.ones(shape=(4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
# metoda full może ustawić konkretne wartości

np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [38]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [40]:
np.arange(start=5, stop=10, step=0.5)

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [41]:
np.arange(start=100, stop=10, step= -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [42]:
np.arange(start = 0, stop = 1, step = 0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [43]:
# num - mówi ile elementów równo rozłozonych chcemy wygenerować z podanego zakresu

np.linspace(start=0, stop=1, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## Zmiana kształtu danych

In [44]:
# reshape

a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [45]:
# ustawiamy na co chcemy zmienić, 15 dzieli się na 3 po 5

a.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [46]:
# - 1 => powoduje, że python sam wybierze ile kolum w posiadanych liczb powstanie, my tylko podajemy liczbę wierszy

a.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
# można też podać na odwrót czyli liczbę kolum a liczba wierszy zostanie automatycznie dobrana

a.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Podstawowe operacje na tablicach

In [48]:
a = np.array([1,2,3,4])
b = np.array([3,-1,3,2])


In [49]:
a

array([1, 2, 3, 4])

In [50]:
b

array([ 3, -1,  3,  2])

In [51]:
a + b

array([4, 1, 6, 6])

In [52]:
a-b

array([-2,  3,  0,  2])

In [53]:
a*b

array([ 3, -2,  9,  8])

In [54]:
a/b

array([ 0.33333333, -2.        ,  1.        ,  2.        ])

In [55]:
a + 3

array([4, 5, 6, 7])

In [56]:
2 * a

array([2, 4, 6, 8])

In [57]:
a + 3 * b

array([10, -1, 12, 10])

In [58]:
np.add(a,b)

array([4, 1, 6, 6])

In [59]:
np.subtract(a,b)

array([-2,  3,  0,  2])

In [60]:
np.multiply(a,b)

array([ 3, -2,  9,  8])

In [61]:
np.divide(a,b)

array([ 0.33333333, -2.        ,  1.        ,  2.        ])

## Mnożenie macierzowe

In [62]:
x = np.array([[1,3], [-2,0]])
y = np.array([[6,0], [-1,2]])

In [63]:
print(x, '\n'), print(y)
#'\n' - linia przerwy

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


(None, None)

In [64]:
x * y

array([[6, 0],
       [2, 0]])

In [65]:
# metoda np.dot() - to mnożenie macierzy

# 1 * 6 + 3 * -1 = 3 - pierwszy wiersz pierwsza kolumna, ________.  1 * 0 + 3 * 2 = 6 - pierwszy wiersz druga kolumna
# -2 * 6 + 0 * -1 = -12 - drugi wiersz pierwsza kolumna     _________     # 1 * 0 + 3 * 0 = 0 - prawy dolny róg - drugi wiersz druga kolumna

#

np.dot(x,y)

# to nam zwraca mnożenie macierzowe, wiersz x kolumna i wiersz x kolumna

array([[  3,   6],
       [-12,   0]])

In [66]:
x.dot(y)

array([[  3,   6],
       [-12,   0]])

In [67]:
y.dot(x)

array([[ 6, 18],
       [-5, -3]])

In [68]:
# liczba kolumn w pierwszej macierzy musi zgadzać się z liczbą wierszy w drugiej macierzy

# [m x n] [n x p]

# w rezultacie dostanę [m x p] - narożne
# monożenie macierzy nie jest przemienne

In [69]:
x = np.array([[5,3], [3,9]])
y = np.array([[1], [-1]])
print(x, '\n'), print(y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


(None, None)

In [70]:
# 2 x 2 i 2 x 1 czyli 2 i dwa się zgadza, wynik 2 x 1 będzie czyli dwa wiersze i jedna kolumna
z = np.dot(x,y)
z

array([[ 2],
       [-6]])

In [71]:
x.dot(y)

array([[ 2],
       [-6]])

In [72]:
z.shape

(2, 1)

In [73]:
y.dot(x) nie wykona się bo rozmiar macierzy się nie zgadza
# mnożenia macierzy niejest przemienne

SyntaxError: ignored

In [74]:
# macierz 2 x 3 i 3 x 3 ok. można mnożyć środek się zgadza, wynikowa macierz będzie miała 2 x 3 czyli dwa wiersze i 3 kolumny
# macierz wynikowa = tyle ile mam wierszy w pierwszej macierzy i tyle ile mam kolumn w drugiej macierzy

x = np.array([[2,-1,3], [3,1,0]])
y = np.array([[2,1,-1], [0,-1,2], [3,2,0]])

print(x, '\n'), print(y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


(None, None)

In [75]:
z = np.dot(x,y)
z

# pierwszy wiersz pierwsza kolumna = 2*2+-1*0+3*3 = 4+9= 13
# pierwszy wiersz druga kolumna = 2*1+-1*-1+3*2 = 9
# pierwszy wiersz trzecia kolumna = 2*-1+-1*2+3*0 = -2+-2+0 = -4
# to wyżej to pierwszy wiersz => 13, 9, -4

# drugi wiersz => 6, 2, -1
# drugi wiersz pierwsza kolumna = 3*2+1*0+0*3 = 6
# drugi wiersz druga kolumna = 3*1+1*-1+0*2 = 2
# drugi wiersz trzecia kolumna = 3*-1+1*2+0*0 = -1


array([[13,  9, -4],
       [ 6,  2, -1]])

## Generowanie liczb pseudolosowych => np.random

In [76]:
np.random.seed(0)

In [78]:
# randn - liczby z rozkładu normalnego, jak nie podam żadnego parametru to zwróci losową wartość

np.random.randn()

0.4001572083672233

In [79]:
# tablica z 10 losowo wygenerowanymi elementami

np.random.randn(10)

array([ 0.97873798,  2.2408932 ,  1.86755799, -0.97727788,  0.95008842,
       -0.15135721, -0.10321885,  0.4105985 ,  0.14404357,  1.45427351])

In [80]:
# tablica składająca sie z 10 wierszy i 4 kolumn

np.random.randn(10,4)

array([[ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877,  0.15494743,  0.37816252],
       [-0.88778575, -1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682, -0.30230275],
       [-1.04855297, -1.42001794, -1.70627019,  1.9507754 ],
       [-0.50965218, -0.4380743 , -1.25279536,  0.77749036],
       [-1.61389785, -0.21274028, -0.89546656,  0.3869025 ]])

In [81]:
# rand - zwróci wartość losową z przedziału 0 - 1

np.random.rand()

0.1965823616800535

In [82]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [83]:
np.random.rand(10,2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [84]:
# randint - zwraca liczbę całkowitą minijszę niż ta podana w nawiasie np 10

np.random.randint(10)

3

In [86]:
# low - parametr startowy, high = 101 - parametr końcowy

np.random.randint(low = 10, high = 101)

56

In [87]:
# size - możemy danych wygenerować tylko ile potrzbujemy

np.random.randint(low = 10, high = 101, size = 10)

array([52, 66, 70, 87, 40, 34, 12, 13, 23, 50])

In [89]:
# funkcja choice - losowo wybiera element z obiektu, który przekażemy

np.random.choice([4,5,4,6,7])

6

In [91]:
np.random.choice(['python', 'javasctipt', 'c++', 'c', 'java'])

'c++'

In [92]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
# można przetasować dane -  shuffle, poniższy kod zmienia nasze dane

np.random.shuffle(data)

In [94]:
data

array([6, 9, 1, 5, 0, 7, 3, 4, 8, 2])